var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 游戏配置表.xlsx SHEET: 皮肤
     */
    var TableSkinConfig = (function () {
        function TableSkinConfig() {
        }
        TableSkinConfig.prototype.GetType = function () { return 'table.TableSkinConfig'; };
        return TableSkinConfig;
    }());
    table.TableSkinConfig = TableSkinConfig;
    __reflect(TableSkinConfig.prototype, "table.TableSkinConfig");
})(table || (table = {}));
//# sourceMappingURL=TableSkinConfig.js.map