var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 游戏配置表.xlsx SHEET: 关卡配置表
     */
    var TableSceneLevelConfig = (function () {
        function TableSceneLevelConfig() {
        }
        TableSceneLevelConfig.prototype.GetType = function () { return 'table.TableSceneLevelConfig'; };
        return TableSceneLevelConfig;
    }());
    table.TableSceneLevelConfig = TableSceneLevelConfig;
    __reflect(TableSceneLevelConfig.prototype, "table.TableSceneLevelConfig");
})(table || (table = {}));
//# sourceMappingURL=TableSceneLevelConfig.js.map