var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 游戏配置表.xlsx SHEET: 全局配置
     */
    var TableGameConfig = (function () {
        function TableGameConfig() {
        }
        TableGameConfig.prototype.GetType = function () { return 'table.TableGameConfig'; };
        return TableGameConfig;
    }());
    table.TableGameConfig = TableGameConfig;
    __reflect(TableGameConfig.prototype, "table.TableGameConfig");
})(table || (table = {}));
//# sourceMappingURL=TableGameConfig.js.map