//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置表.xlsx SHEET: 背景
	 */
	export class TableBackgroundConfig {
		/**
		 * 背景ID
		 */
		id: number;
		/**
		 * 获得条件
		 */
		unlockType: number;
		/**
		 * 条件值
		 */
		unlockValue: number;

		GetType(): string { return 'table.TableBackgroundConfig'; }
	}
}
