//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置表.xlsx SHEET: 关卡配置表
	 */
	export class TableSceneLevelConfig {
		/**
		 * 关卡等级
		 */
		level: number;
		/**
		 * 数字分布
		 */
		digits: number[];
		/**
		 * 数字分布权重
		 */
		digitalWeights: number[];
		/**
		 * 颜色分布权重
		 */
		colorWeights: number[];
		/**
		 * 步数
		 */
		step: number;
		/**
		 * 目标达成分数
		 */
		scores: number[];
		/**
		 * 通关奖励
		 */
		winChips: number;

		GetType(): string { return 'table.TableSceneLevelConfig'; }
	}
}
