//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置表.xlsx SHEET: 全局配置
	 */
	export class TableGameConfig {
		/**
		 * 签到
		 */
		signs: number[];
		/**
		 * 增加步数消耗金币数
		 */
		chipsRewardStep: number[];
		/**
		 * 观看一次视频赠送步数
		 */
		videoRewardStep: number;
		/**
		 * 任意消除一次消耗金币数
		 */
		chipsReduceReward: number;

		GetType(): string { return 'table.TableGameConfig'; }
	}
}
